### PR TITLE
Add Validation Unique NIM and rename logistik to Logistik

### PR DESCRIPTION
**Pull request by adhiiimf**
Add feature to prevented double nim when create caas account

### CODE REVIEW

**Comment by IritaSee** [comment]
Adding myself again as a reviewer since @fakhrip is kind of not responding and it is only a small update

**Comment by adhiiimf** [comment]
I want to close PR to add README.md

**Review by IritaSee — CHANGES_REQUESTED** [review]
I saw that there are two codes having the same functionality inside the controller and hardcoded in the blade template, please choose one that works better. For me it is the one using controller so you can put some other error messages inside. And also don't forget the readme file okay

**Comment by IritaSee** [comment]
I think it is better for us to make a single solid pull request instead of multiple small pull requests. I am closing this one so you can add more changes into it and make a more solid request. ^^

**Comment by IritaSee** [comment]
And also since we are using composer that kind of having a bit issue in dependency today, I've been enabled the dependabot, but please look up for the version before merging dependabot requests, since the rest of the project in our deployment environment is kind of sensitive with that. ^^ cheers

**Pull request closed without merging**
