### PR TITLE
Renew Datacaas Validation, Logistik, and Readme.md

### PR DESCRIPTION
**Pull request by adhiiimf**
### UPDATE Datacaas
- Validate for unique nim when admin create caas Account.
- Error message if unique detected.

### Logistik File Name
- Rename case-sensitive logistik to Logistik

### Renew README.md
- Update Content of Readme.md

Pull Request by @adhiiimf

### CODE REVIEW

**Review by IritaSee — APPROVED** [review]
Good~l ove these new validation process, tell me when you are ready to release them to production stage

**Comment by adhiiimf** [comment]
Thank you @IritaSee

**Comment by fakhrip** [comment]
> ### UPDATE Datacaas
> 
>     * Validate for unique nim when admin create caas Account.
> 
>     * Error message if unique detected.
> 
> 
> ### Logistik File Name
> 
>     * Rename case-sensitive logistik to Logistik
> 
> 
> ### Renew README.md
> 
>     * Update Content of Readme.md
> 
> 
> Pull Request by @adhiiimf

Cool, but just a little thing to have in mind that `Pull Request by @adhiiimf` is not needed as its already obvious this was created by yourself @adhiiimf, don't put it next time in another PR okay

**Comment by fakhrip** [comment]
Also im really sorry, im having too many things to do these times around, so its amazing to have you cover this things @IritaSee, thanks iga :+1:

**Comment by IritaSee** [comment]
That is totally okay @fakhrip , we need to cooperate more to solve more

**Pull request merged**
