### PR TITLE
change OA Line link

### PR DESCRIPTION
**Pull request by adhiiimf**
### OA Line link
this `PR` about change links to access Official Account recruitment to general daskom line

devkom'19,
_Adhi MF_

### CODE REVIEW

**Review by IritaSee — APPROVED** [review]
ahh we changed the line official account already? Time flies~

**Comment by IritaSee** [comment]
Small one, merging...

**Comment by fakhrip** [comment]
> ahh we changed the line official account already? Time flies~

i feel old :(

**Comment by adhiiimf** [comment]
> > ahh we changed the line official account already? Time flies~
> 
> i feel old :(

wkwkwk not general official account, but recruitment 2021 account changed to general to hide all post about 2021 recruitment haha

**Pull request merged**
