### PR TITLE
Adhidev PR to upgrade and improve some features in recruitment.daskomlab.com

### PR DESCRIPTION
**Pull request by adhiiimf**
### Data Type for table  messagecekluluses
- change datatype _string_ to _text_ on column **lolostext** and **notlolostext** (coz string has max string 255 char).
### Database Seeder Update
- Move Seeder Function of Messagecekluluses from DatabaseSeeder to MessageceklulusSeeder.
### Update Blade
- Modify Blade `{{}}` to `{!!nl2sn(e())!!}}` for variabel `$lolostext` and `$failedtext` (to able use `<br>`),
- Modify _width value_ for `home-button:hover`,
- Add Animation with for landing page,
- Add background-color for body in landing page,
- and modify text for footer.

i think it's enough, thankyou
**_Adhidev [AMF]_**

### CODE REVIEW

**Review by fakhrip — APPROVED** [review]
Dont forget to create a new migration for any changes related to table and database structure for next time :+1:

**Comment by IritaSee** [comment]
New migration script added and supervised. Merge and deploy scheduled in Saturday (22 May 2021)

**Comment by adhiiimf** [comment]
Thankyou master @fakhrip and master @IritaSee 😁🙏

**Comment by IritaSee** [comment]
Successfully merge files in live server, application is now a go

**Pull request merged**
